
using AirplaneBooking.Application.Interfaces.Repositories; // This allows it to implement IBookingRepository
using AirplaneBooking.Domain.Entities; // To use the Booking and Passenger domain entities
using MongoDB.Driver; // For MongoDB operations
using Microsoft.Extensions.Logging; // For logging
using MongoDB.Bson; // For BsonRepresentation
using MongoDB.Bson.Serialization.Attributes; // For BsonId and BsonRepresentation
using global::AirplaneBooking.Infrastructure.Persistence;

namespace AirplaneBooking.Infrastructure.Repositories;

// AirplaneBooking.Infrastructure/Persistence/Repositories/MongoDbBookingRepository.cs

using MongoDB.Driver; // For MongoDB operations
using Microsoft.Extensions.Logging; // For logging
using MongoDB.Bson; // For BsonRepresentation
using MongoDB.Bson.Serialization.Attributes; // For BsonId and BsonRepresentation
using System; // <--- ADDED: For DateTime, Exception, ArgumentNullException
using System.Collections.Generic; // <--- ADDED: For List
// Removed global:: using as it's not needed here
using AirplaneBooking.Infrastructure.Persistence; // For MongoDbContext
    public class MongoBookingModel
    {
        [BsonId] // Designates this as the primary key field for MongoDB
        [BsonRepresentation(BsonType.ObjectId)] // Specifies that the Id should be stored as MongoDB's ObjectId type
        public string Id { get; set; } // This will be the MongoDB generated ObjectId

        public string FirebaseBookingId { get; set; } // To link back to the Firebase ID
        public string UserId { get; set; }
        public string FlightId { get; set; }
        public List<Passenger> Passengers { get; set; } // Reusing Domain Passenger entity directly
        public decimal TotalPrice { get; set; }
        public DateTime BookingDate { get; set; }
        public string Status { get; set; }
        public string AmadeusBookingReference { get; set; }
        public DateTime LastUpdated { get; set; } = DateTime.UtcNow; // New field for MongoDB

        // Add any other specific fields for MongoDB if your schema differs greatly from Domain.Booking
    }

    // MongoDbBookingRepository will implement IBookingRepository (for broad repository methods)
    // and also IMongoDbBookingRepository (for specific methods used by BookingService)
    public class MongoDbBookingRepository : IBookingRepository, IMongoDbBookingRepository // <--- Modified interface implementation
    {
        private readonly IMongoCollection<MongoBookingModel> _bookingsCollection;
        private readonly ILogger<MongoDbBookingRepository> _logger;

        public MongoDbBookingRepository(MongoDbContext context, ILogger<MongoDbBookingRepository> logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _bookingsCollection = context.GetCollection<MongoBookingModel>("Bookings"); // "Bookings" is the collection name in MongoDB
        }

        public async Task AddAsync(Booking booking)
        {
            try
            {
                // Map the Domain.Booking entity to your MongoBookingModel
                var mongoBooking = new MongoBookingModel
                {
                    FirebaseBookingId = booking.Id, // Store the ID generated by Firebase as a foreign key
                    UserId = booking.UserId,
                    FlightId = booking.FlightId,
                    Passengers = booking.Passengers, // Ensure Passenger is also serializable to BSON
                    TotalPrice = booking.TotalPrice,
                    BookingDate = booking.BookingDate,
                    Status = booking.Status,
                    AmadeusBookingReference = booking.AmadeusBookingReference,
                    LastUpdated = DateTime.UtcNow
                };
                await _bookingsCollection.InsertOneAsync(mongoBooking);
                _logger.LogInformation($"Booking from Firebase ID {booking.Id} added to MongoDB with generated Mongo ID {mongoBooking.Id}.");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error adding booking {booking.Id} to MongoDB.");
                throw; // Re-throw the exception for upper layers to handle
            }
        }

        public async Task<Booking> GetByIdAsync(string id)
        {
            try
            {
                // Assuming 'id' here refers to FirebaseBookingId for retrieval consistency
                var filter = Builders<MongoBookingModel>.Filter.Eq(b => b.FirebaseBookingId, id);
                var mongoBooking = await _bookingsCollection.Find(filter).FirstOrDefaultAsync();

                if (mongoBooking == null) return null;

                // Map MongoBookingModel back to Domain.Booking entity
                return new Booking(
                    id: mongoBooking.FirebaseBookingId, // Use the Firebase ID as the Domain ID
                    userId: mongoBooking.UserId,
                    flightId: mongoBooking.FlightId,
                    passengers: mongoBooking.Passengers,
                    totalPrice: mongoBooking.TotalPrice,
                    bookingDate: mongoBooking.BookingDate,
                    status: mongoBooking.Status,
                    amadeusBookingReference: mongoBooking.AmadeusBookingReference
                );
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error getting booking {id} from MongoDB.");
                throw;
            }
        }

        public async Task UpdateAsync(Booking booking)
        {
            try
            {
                var filter = Builders<MongoBookingModel>.Filter.Eq(b => b.FirebaseBookingId, booking.Id);
                var update = Builders<MongoBookingModel>.Update
                    .Set(b => b.Status, booking.Status)
                    .Set(b => b.AmadeusBookingReference, booking.AmadeusBookingReference)
                    .Set(b => b.TotalPrice, booking.TotalPrice)
                    .Set(b => b.LastUpdated, DateTime.UtcNow);

                var result = await _bookingsCollection.UpdateOneAsync(filter, update);
                if (result.ModifiedCount > 0)
                {
                    _logger.LogInformation($"Booking from Firebase ID {booking.Id} updated in MongoDB.");
                }
                else
                {
                    _logger.LogWarning($"Booking from Firebase ID {booking.Id} not found for update in MongoDB.");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error updating booking {booking.Id} in MongoDB.");
                throw;
            }
        }

        public async Task DeleteAsync(string id)
        {
            try
            {
                var filter = Builders<MongoBookingModel>.Filter.Eq(b => b.FirebaseBookingId, id);
                var result = await _bookingsCollection.DeleteOneAsync(filter);
                if (result.DeletedCount > 0)
                {
                    _logger.LogInformation($"Booking from Firebase ID {id} deleted from MongoDB.");
                }
                else
                {
                    _logger.LogWarning($"Booking from Firebase ID {id} not found for deletion in MongoDB.");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error deleting booking {id} from MongoDB.");
                throw;
            }
        }
    }